### ISSUE TITLE
Use the Clipboard API, instead of execCommand

### ISSUE THREAD

**Issue by SiddharthSham** [rohinivsenthil/stackcopy#1]
The `document.exec('copy')` API is deprecated, and also is not supported in Safari. Using the `Clipboard API`  (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)) overcomes this, and will improve performance for larger snippets, as it runs asynchronously.

**Comment by rohinivsenthil** [comment]
Hey, Sid. Thanks for pointing this out! Fixed this.
